version: 2

aliases:
  - &pollsapi-image
    image: circleci/python:3.7
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      PORT: 8000

  - &database-image
    image: circleci/postgres:9.6.2
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: circle_test

  - &bootstrap
    run:
      command: |
        pipenv install
        pipenv run python manage.py migrate
        pipenv run python manage.py loaddata initial_data

workflows:
  version: 2

  pollsapi:
    jobs:
      - test
      - test-dredd

jobs:
  test:
    docker:
      - <<: *pollsapi-image
      - <<: *database-image

    steps:
      - checkout
      - <<: *bootstrap
      - run:
          command: |
            pipenv run python manage.py test

  test-dredd:
    docker:
      - <<: *pollsapi-image
        image: circleci/python:3.7-node-browsers
      - <<: *database-image

    steps:
      - checkout
      - run:
          command: npm install dredd --no-optional
      - <<: *bootstrap
      - run:
          command: |
            pipenv run ./node_modules/.bin/dredd
